create database agenda;

use agenda;

CREATE TABLE STUDENT (
	ID_STUDENT INT(5) AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(120),
	RA VARCHAR(15),
	LOGIN VARCHAR(50),
	PASSWORD VARCHAR(8),
	IS_ADMIN TINYINT,
	ACTIVE TINYINT
);

CREATE TABLE EVENTS (
	ID_STUDENT INT(5),
	ID_EVENT INT(8) NOT NULL,
	DESCRIPTION VARCHAR(300),
	DT_EVENT DATETIME,
	ACTIVE TINYINT,
	CONSTRAINT PK_EVENTS PRIMARY KEY (ID_STUDENT, ID_EVENT),
	CONSTRAINT FK_TASK_IDSTUDENT FOREIGN KEY(ID_STUDENT) REFERENCES STUDENT (ID_STUDENT)
);

INSERT INTO STUDENT (NAME, RA, LOGIN, PASSWORD, IS_ADMIN, ACTIVE)
VALUES ('Bruno Oliveira','170147','bso','rsq1MNZJ', 1, 1);
	
INSERT INTO EVENTS (ID_EVENT, DESCRIPTION, DT_EVENT, ACTIVE, ID_STUDENT)
VALUES ((SELECT T.CODE FROM (SELECT COALESCE(MAX(ID_EVENT), 0) + 1 AS CODE FROM EVENTS WHERE ID_STUDENT = 1) AS T), 'Prova de ADM de BD', '2018-05-25', 1, 1);
INSERT INTO EVENTS (ID_EVENT, DESCRIPTION, DT_EVENT, ACTIVE, ID_STUDENT)
VALUES ((SELECT T.CODE FROM (SELECT COALESCE(MAX(ID_EVENT), 0) + 1 AS CODE FROM EVENTS WHERE ID_STUDENT = 1) AS T), 'Trabalho de Lab 3', '2018-05-22 00:00:00', 1, 1);
INSERT INTO EVENTS (ID_EVENT, DESCRIPTION, DT_EVENT, ACTIVE, ID_STUDENT)
VALUES ((SELECT T.CODE FROM (SELECT COALESCE(MAX(ID_EVENT), 0) + 1 AS CODE FROM EVENTS WHERE ID_STUDENT = 1) AS T), 'Exame oral de ingles', '2018-06-12 19:00:00', 1, 1);